name: Publish release candidate
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]'

jobs:
  publish-release-candidate:
    name: Publish GitHub release candidate
    uses: ./.github/workflows/publish-release-type.yaml
    with:
      isReleaseCandidate: true
      name: release candidate
    secrets:
      githubToken: ${{ secrets.EKSCTLBOT_TOKEN }}
    permissions: 
      contents: write
      pull-requests: write
