name: Publish Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test-and-build:
    uses: ./.github/workflows/test-and-build.yaml
  publish-release:
    name: Publish GitHub release
    uses: ./.github/workflows/publish-release-type.yaml
    needs: [test-and-build]
    with:
      isReleaseCandidate: false
      name: release
    secrets:
      githubToken: ${{ secrets.EKSCTLBOT_TOKEN }}
    permissions: 
      contents: write
      pull-requests: write